src/main/java/com/conveyal/gtfs/GTFSCache.java

Currently running gtfsCache can balloon the local disk with cache and zip files.  This keeps them under control by deleting them onRemoval if (and only if) s3 is being used (so we have remote backups).

add delete on removal for local cache files

---

src/main/java/com/conveyal/gtfs/model/Service.java
src/main/java/com/conveyal/gtfs/validator/OverlappingTripsValidator.java

fix bug where check for date in both service ids did not previously check exception_type

Fix bug with overlapping trips validator

---

src/main/java/com/conveyal/gtfs/model/Agency.java
src/main/java/com/conveyal/gtfs/model/Calendar.java
src/main/java/com/conveyal/gtfs/model/CalendarDate.java
src/main/java/com/conveyal/gtfs/model/Entity.java
src/main/java/com/conveyal/gtfs/model/FareAttribute.java
src/main/java/com/conveyal/gtfs/model/FareRule.java
src/main/java/com/conveyal/gtfs/model/FeedInfo.java
src/main/java/com/conveyal/gtfs/model/Frequency.java
src/main/java/com/conveyal/gtfs/model/Route.java
src/main/java/com/conveyal/gtfs/model/Service.java
src/main/java/com/conveyal/gtfs/model/ShapePoint.java
src/main/java/com/conveyal/gtfs/model/Stop.java
src/main/java/com/conveyal/gtfs/model/StopTime.java
src/main/java/com/conveyal/gtfs/model/Transfer.java
src/main/java/com/conveyal/gtfs/model/Trip.java

Use auto-generated serialVersionUIDs from v1.4.0.

fix(model): add serialVersionUID to model classes

---

pom.xml

fix(build): fix slf4j import/exclusion, and remove duplicate trove4j dep

---

src/main/java/com/conveyal/gtfs/model/Agency.java

Add missing `agency_email` field to Agency.java.  fixes #48

fix(Agency): add missing agency_email field

---

.travis.yml

* See https://github.com/conveyal/gtfs-lib/pull/47#issuecomment-300578909 and https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

Fix Travis PR builds by not executing openssl command

---

src/main/java/com/conveyal/gtfs/util/json/JsonManager.java

* Refactor filters variable to be class member so it can be re-used later with ObjectMapper member variable for pretty print
* Rename writer/mapper variables to make it clearer which is being used
* Fix Javadoc for constructor

Fix #46 - Use filter when writing pretty print JSON

---

src/main/java/com/conveyal/gtfs/BaseGTFSCache.java
src/main/java/com/conveyal/gtfs/GTFSCache.java

For accessing feeds directly in the GTFSCache here and the FeedSourceCache in the GTFS API.

Add abstract getFeed function to BaseGTFSCache

---

src/main/java/com/conveyal/gtfs/loader/JDBCTableReader.java

This PR maps `sql_table.csv_line` to `Entity.sourceFileLine`.
Fixes #71.

map csv_line to Entity#sourceFileLine

---

.travis.yml
src/main/java/com/conveyal/gtfs/GTFS.java
src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java
src/main/java/com/conveyal/gtfs/error/SQLErrorStorage.java
src/main/java/com/conveyal/gtfs/loader/BooleanField.java
src/main/java/com/conveyal/gtfs/loader/ColorField.java
src/main/java/com/conveyal/gtfs/loader/CurrencyField.java
src/main/java/com/conveyal/gtfs/loader/EntityPopulator.java
src/main/java/com/conveyal/gtfs/loader/Feed.java
src/main/java/com/conveyal/gtfs/loader/IntegerField.java
src/main/java/com/conveyal/gtfs/loader/JDBCTableReader.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
src/main/java/com/conveyal/gtfs/loader/ShortField.java
src/main/java/com/conveyal/gtfs/loader/TimeField.java
src/main/java/com/conveyal/gtfs/model/Agency.java
src/main/java/com/conveyal/gtfs/model/Calendar.java
src/main/java/com/conveyal/gtfs/model/CalendarDate.java
src/main/java/com/conveyal/gtfs/model/FareAttribute.java
src/main/java/com/conveyal/gtfs/model/FareRule.java
src/main/java/com/conveyal/gtfs/model/Route.java
src/main/java/com/conveyal/gtfs/model/ShapePoint.java
src/main/java/com/conveyal/gtfs/model/Transfer.java
src/main/java/com/conveyal/gtfs/model/Trip.java
src/main/java/com/conveyal/gtfs/storage/StorageException.java
src/main/java/com/conveyal/gtfs/validator/NewTripTimesValidator.java
src/main/java/com/conveyal/gtfs/validator/ServiceValidator.java

- Use symbolic constant `INT_MISSING` for missing ints in GTFS entities
- implement `getId` and `getSequenceNumber` abstract methods for Entity classes
- handle non-UTF-8 character encodings

Numerous validation error fixes

---

src/test/java/com/conveyal/gtfs/util/UtilTest.java

Set locale to US on humanize test

---

src/main/java/com/conveyal/gtfs/error/SQLErrorStorage.java
src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
src/main/java/com/conveyal/gtfs/graphql/fetchers/FeedFetcher.java
src/main/java/com/conveyal/gtfs/graphql/fetchers/JDBCFetcher.java
src/main/java/com/conveyal/gtfs/graphql/fetchers/NestedJDBCFetcher.java
src/main/java/com/conveyal/gtfs/graphql/fetchers/RowCountFetcher.java
src/main/java/com/conveyal/gtfs/loader/EntityPopulator.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java
src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
src/main/java/com/conveyal/gtfs/loader/Table.java
src/main/java/com/conveyal/gtfs/model/Entity.java
src/main/java/com/conveyal/gtfs/model/ScheduleException.java
src/main/java/com/conveyal/gtfs/validator/NewTripTimesValidator.java
src/main/java/com/conveyal/gtfs/validator/PatternFinderValidator.java

This PR contains a number of bug fixes for pattern editing (as well as other components of the editor) and massively improves the performance of table snapshotting.

Performance improvements + bug fixes for editor

---

.travis.yml

These additional commands are required to make commits and merge master into dev

ci(semantic-release): update travis command for maven-semantic-release

---

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java

Refs catalogueglobal/datatools-ui#266. This is the last of the added fields from #99.

Add Fare#agency_id to GraphQL spec

---

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java

This fixes and simplifies the data structures used in the snapshotting process to create schedule exceptions from calendar dates. Fixes #161.

Fix duplicated schedule exceptions issue with multimap

---

src/main/java/com/conveyal/gtfs/validator/NamesValidator.java
src/main/java/com/conveyal/gtfs/validator/SpeedTripValidator.java

Speed up name validation and fixes shape_dist_traveled check

---

src/main/java/com/conveyal/gtfs/model/Route.java

Merging quickly due to project time constraints.

Fix entity add route#route_sort_order to setStatementParameters

---

pom.xml
src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
src/main/java/com/conveyal/gtfs/model/Pattern.java
src/main/java/com/conveyal/gtfs/validator/PatternFinderValidator.java
src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchPatterns.json
src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchRoutes.json
src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canSanitizeSQLInjectionSentAsKeyValue.json

Fix pattern#direction_id import and route_type field type

---

.travis.yml

N/A - fix is just to travis config
This PR contains changes to the travis config that will hopefully fix #193.

Properly run codecov to report coverage on master

---

.travis.yml

Seeks to merge #197 into master.

Merge codecov changes into master

---

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java

Fixes conveyal/datatools-server#154.

Create feed registry if not exists when snapshotting

---

.github/CODEOWNERS
.github/issue_template.md
.github/pull_request_template.md

N/A - no changes to java code
N/A - PR not related to code changes
Adds issue and PR templates as suggested in #194.

Add codeowners, issue and pr templates

---

src/main/java/com/conveyal/gtfs/loader/DateListField.java
src/test/java/com/conveyal/gtfs/dto/ScheduleExceptionDTO.java
src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java

Contains a single bug fix from #215.

Bug fix PR

---

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java
src/main/java/com/conveyal/gtfs/loader/Table.java

Fixes #221 by moving `Table#checkReferencesAndUniqueness` to `ReferenceTracker#checkReferencesAndUniqueness`.

Refactor reference tracker

---

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java
src/main/java/com/conveyal/gtfs/loader/Table.java

Bug fix release containing #221.

Bug fix release

---

src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java

This PR adds a `fix` commit in order to trigger a bug fix release to contain #221. #224 was intended to trigger this release, but omitted the `fix` commit by accident.

Trigger bug fix release

---

src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java
src/main/java/com/conveyal/gtfs/loader/Table.java

Fixes #231. Also, adds dropoff/pickup type = 3 for stop_times table.

Fix calendar_date#service_id ref integrity issue and add pickup/dropoff value

---

src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java
src/test/java/com/conveyal/gtfs/dto/FareDTO.java
src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java

Fixes conveyal/datatools-ui#346. Also, improves a test to verify this works.

Fix issue w empty fare_attributes#transfers val

---

src/main/java/com/conveyal/gtfs/model/Entity.java
src/main/java/com/conveyal/gtfs/model/Route.java
src/main/java/com/conveyal/gtfs/model/Stop.java
src/main/java/com/conveyal/gtfs/model/Trip.java
src/test/java/com/conveyal/gtfs/GTFSMainTest.java
src/test/resources/fake-agency-bad-calendar-date/routes.txt

Fix NPE in GTFSFeed loading of entity with null id

---

.travis.yml
src/main/java/com/conveyal/gtfs/GTFS.java
src/main/java/com/conveyal/gtfs/error/SQLErrorStorage.java
src/main/java/com/conveyal/gtfs/loader/JDBCTableReader.java
src/main/java/com/conveyal/gtfs/loader/JdbcGTFSFeedConverter.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java
src/main/java/com/conveyal/gtfs/validator/PatternFinderValidator.java
src/test/java/com/conveyal/gtfs/GTFSTest.java
src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java

Fixes create feed registry SQL and adds delete feed stage/assertions to integration test. Fix #248.
Note: existing databases will need to add the column `deleted` to the feed registry table:
```SQL
ALTER TABLE feeds ADD COLUMN deleted boolean;
```

Fix delete feed

---

.travis.yml
src/main/java/com/conveyal/gtfs/GTFS.java
src/main/java/com/conveyal/gtfs/error/SQLErrorStorage.java
src/main/java/com/conveyal/gtfs/loader/JDBCTableReader.java
src/main/java/com/conveyal/gtfs/loader/JdbcGTFSFeedConverter.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java
src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java
src/main/java/com/conveyal/gtfs/validator/PatternFinderValidator.java
src/test/java/com/conveyal/gtfs/GTFSTest.java
src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java

Bug fix/patch release. Includes:
- #249
- #252

New release

---

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
src/main/java/com/conveyal/gtfs/loader/Table.java
src/main/java/com/conveyal/gtfs/model/FeedInfo.java
src/test/java/com/conveyal/gtfs/GTFSTest.java
src/test/java/com/conveyal/gtfs/dto/FeedInfoDTO.java
src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java
src/test/resources/fake-agency/feed_info.txt

Add feed_id to JDBC code path

---

src/main/java/com/conveyal/gtfs/loader/Table.java

Change transfers#transfer_type column to ShortField

---

.travis.yml

Clear target directory before running maven-semantic-release.

Attempt to fix issue where mult. builds deployed to maven central

---

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
src/main/java/com/conveyal/gtfs/graphql/fetchers/ErrorCountFetcher.java
src/test/resources/graphql/feedErrors.txt
src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchErrors-0.json

Next release

---

src/main/java/com/conveyal/gtfs/GTFS.java
src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java
src/main/java/com/conveyal/gtfs/loader/Table.java
src/test/java/com/conveyal/gtfs/GTFSTest.java
src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java
src/test/java/com/conveyal/gtfs/storage/RecordExpectation.java

Includes a fix for snapshots to avoid modifying `stop_times#stop_sequence` values (from PR #285).

Bug fix release (add normalize stop times flag)

---

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
src/main/java/com/conveyal/gtfs/graphql/fetchers/PolylineFetcher.java
src/main/java/com/conveyal/gtfs/util/PolylineUtils.java
src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java
src/test/java/com/conveyal/gtfs/util/PolylineUtilsTest.java
src/test/resources/graphql/feedPolylines.txt
src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchPolylines-0.json

re ibi-group/datatools-ui#627
Adds encoded polyline utils (from Mapbox repo) and GraphQL query for shapes as encoded polylines.

Add graphql fetcher for shapes as encoded polylines

---

pom.xml
src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
src/main/java/com/conveyal/gtfs/graphql/fetchers/PolylineFetcher.java
src/main/java/com/conveyal/gtfs/util/PolylineUtils.java
src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java
src/test/java/com/conveyal/gtfs/util/PolylineUtilsTest.java
src/test/resources/graphql/feedPolylines.txt
src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchPolylines-0.json

New feature release (polyline fetcher). Includes PRs #292 and #297.

Feature release

---

pom.xml

This is a dummy PR to trigger a maven deploy of v6.2.1 (v6.2.0 failed).

Update developer info

---

pom.xml
src/test/java/com/conveyal/gtfs/GTFSFeedTest.java
src/test/java/com/conveyal/gtfs/GTFSMainTest.java
src/test/java/com/conveyal/gtfs/GTFSTest.java
src/test/java/com/conveyal/gtfs/GeometriesTest.java
src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java
src/test/java/com/conveyal/gtfs/loader/FieldTests.java
src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java
src/test/java/com/conveyal/gtfs/storage/BooleanAsciiGridTest.java
src/test/java/com/conveyal/gtfs/util/PolylineUtilsTest.java
src/test/java/com/conveyal/gtfs/util/UtilTest.java
src/test/java/com/conveyal/gtfs/validator/MTCValidatorTest.java
src/test/java/com/conveyal/gtfs/validator/ServiceValidatorTest.java
src/test/java/com/conveyal/gtfs/validator/SpeedTripValidatorTest.java

This PR aims to update JUnit from version 4 to version 5. This includes updating all JUnit references (e.g. Test, BeforeClass, Before etc), updating deprecated classes (e.g. to the org.hamcrest package) and "expect system exit" third party lib.
This PR is a prerequisite https://github.com/ibi-group/datatools-server/issues/362

JUnit Upgrade

---

src/main/java/com/conveyal/gtfs/model/StopTime.java

Adds hashcode and equals method for use in https://github.com/ibi-group/datatools-server/pull/376

Add hashCode and equals method to StopTime.java

---

src/main/java/com/conveyal/gtfs/loader/Table.java
src/main/java/com/conveyal/gtfs/loader/conditions/AgencyHasMultipleRowsCheck.java
src/main/java/com/conveyal/gtfs/loader/conditions/ConditionalRequirement.java
src/main/java/com/conveyal/gtfs/loader/conditions/FieldInRangeCheck.java
src/main/java/com/conveyal/gtfs/loader/conditions/FieldIsEmptyCheck.java
src/main/java/com/conveyal/gtfs/loader/conditions/FieldNotEmptyAndMatchesValueCheck.java
src/main/java/com/conveyal/gtfs/loader/conditions/ForeignRefExistsCheck.java
src/main/java/com/conveyal/gtfs/loader/conditions/ReferenceFieldShouldBeProvidedCheck.java

This PR refactors the `ConditionRequirement` class further by moving subclass-specific fields to those subclasses. It also fixes what seems to be an error in the logic within the `FieldNotEmptyAndMatchesValueCheck` check method.

Remove unneeded arguments from ConditionalRequirements classes

---

.github/workflows/maven.yml

- [na] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
This PR updates node for semantic-release to import correctly in the CI builds.

ci(maven.yml): Update to node 14 for using semantic-release.
