conveyal/gtfs-lib

pom.xml, src/main/java/com/conveyal/gtfs/model/CalendarDate.java, src/main/java/com/conveyal/gtfs/model/Entity.java, src/main/java/com/conveyal/gtfs/model/Fare.java, src/main/java/com/conveyal/gtfs/model/FeedInfo.java, src/main/java/com/conveyal/gtfs/model/Service.java
This fully removes Joda from gtfs-lib and makes it java 8 library since it needs java 8 date and time classes.
I removed Joda because I removed it also in r5: conveyal/r5#10.
When this is merged r5 also needs to be updated.
=> Remove Joda and replace it with Java 8 time classes

src/main/java/com/conveyal/gtfs/GTFSMain.java, src/main/java/com/conveyal/gtfs/error/EmptyTableError.java, src/main/java/com/conveyal/gtfs/model/Entity.java, src/main/java/com/conveyal/gtfs/util/json/JsonManager.java
- adds empty table error when a table has no rows or only header
- pretty prints json validation errors (if validate flag used)
=> Add empty table error, pretty print json validation

src/main/java/com/conveyal/gtfs/error/NoAgencyInFeedError.java, src/main/java/com/conveyal/gtfs/error/NoOperatorInFeedError.java, src/main/java/com/conveyal/gtfs/model/Route.java
This fix is for feeds that have no agency records. When the agency_id for a route has a missing
reference, it is assigned the first agency if there is only one agency. If there are no agencies
present, the field is left null and a NoOperatorInFeedError is stored.
Fixes #40
=> fix(Route): Fix agency NPE issue

src/main/java/com/conveyal/gtfs/GTFSFeed.java
* See "Conclusion" of https://blogs.oracle.com/dholmes/entry/inside_the_hotspot_vm_clocks, which says:
>If you are interested in measuring/calculating elapsed time, then always use System.nanoTime().
=> Use System.nanoTime() to measure elapsed time

src/main/java/com/conveyal/gtfs/model/FareAttribute.java
Missing transfers means "unlimited" in this case use value grater-than 2 (for now i supplies/mapped it to 3), rather than 0. As 0 already has some meaning, so it cause bug/mislead the lib user.
=> Fare Attributes : missing transfers means "unlimited"

pom.xml, src/main/java/com/conveyal/gtfs/graphql/GTFSGraphQL.java, src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/graphql/GraphQLUtil.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/ErrorCountFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/FeedFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/JDBCFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/MapFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/RowCountFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/SQLColumnFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/SourceObjectFetcher.java, src/main/java/com/conveyal/gtfs/graphql/package-info.java
It used to be in a separate project called gtfs-api.
We just put the Java graphql api definition in this project, which takes string queries and returns Object responses.
Whatever project includes gtfs-lib will need to provide an HTTP layer on top of this using some web server or framework.
=> Integrate graphql API directly into gtfs-lib

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/main/java/com/conveyal/gtfs/validator/PatternFinderValidator.java
- This allows for fetching GTFS stop entities that are served by a pattern or a route nested underneath one of these entities.
- This allows for the creation of a "blank" snapshot, i.e., the full set of tables required for GTFS editing with no rows.
=> A few fixes for the GTFS Editor

src/main/java/com/conveyal/gtfs/GTFSFeed.java, src/main/java/com/conveyal/gtfs/PatternFinder.java, src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/main/java/com/conveyal/gtfs/model/Pattern.java, src/main/java/com/conveyal/gtfs/validator/ServiceValidator.java
This fixes gtfs-lib for usage in r5.  The primary thing broken during the SQL load/edit enhancements was `GTFSFeed#findPatterns`, which was never re-implemented using the new `PatternFinder` class. This temporarily patches this so that r5 does not break when using the latest `gtfs-lib`.
=> Re-implement findPatterns method in MapDB GTFSFeed using storage-agnostic PatternFinder

src/main/java/com/conveyal/gtfs/TripPatternKey.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/main/java/com/conveyal/gtfs/loader/Requirement.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/main/java/com/conveyal/gtfs/validator/PatternFinderValidator.java
This PR adds the GTFS editor feature that filters out un-approved routes when exporting a snapshot to GTFS.  This is achieved by embedding filtering select statements into the `COPY TO` SQL.  These filters select only those routes with `status = 2` (i.e., route is approved) and joins this selection of routes to related tables (specifically, trips, stop_times, and shapes).
It also addresses a bug where duplicate row headers or headers named `id` cause a table load failure.
=> Filter approved routes when exporting from GTFS editor

src/main/java/com/conveyal/gtfs/loader/EntityPopulator.java, src/main/java/com/conveyal/gtfs/loader/Field.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/main/java/com/conveyal/gtfs/validator/ServiceValidator.java
This fixes the following:
- [Per the GTFS spec](https://developers.google.com/transit/gtfs/reference/#agencytxt), agency ID can be empty if there is only one agency in the feed.  This fix allows this empty value when editing agencies iff there is one agency.
- Multiple calendar_dates rows with the same `service_id` value should not cause duplicate ID errors to be recorded.
- Allow empty `transfers` field fare_attributes table
- Handle null ints when filling values in `EntityPopluator`
=> Allow null agency_id; fix calendar_dates false duplicate service_id

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/graphql/GraphQLUtil.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/JDBCFetcher.java, src/main/java/com/conveyal/gtfs/loader/DateField.java, src/main/java/com/conveyal/gtfs/loader/EntityPopulator.java, src/main/java/com/conveyal/gtfs/loader/Field.java, src/main/java/com/conveyal/gtfs/loader/JdbcGTFSFeedConverter.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java, src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/main/java/com/conveyal/gtfs/loader/Table.java
This PR adds support for GraphQL-based bounding box queries for both GTFS stops and patterns.  It does this by simply chaining conditions onto the where clause constructed for the SQL query.
It also adds string search for stops (on stop_id, stop_code, and stop_name) and routes (route_id, route_short_name, and route_long_name).  A column metadata query ensures that the route or stop table has the respective search fields before issuing a query to them.
This adds missing code to reconcile stop times to any changes to pattern stops (i.e., additions, deletions, transpositions) as well as linking pattern stops fields to stop times (e.g., timepoint, pickup or drop off).  Other tables with redundant data are also "linked", including trips which inherits `wheelchair_accessible` from routes and …
=> Add bounding box and string search GraphQL queries; Reconcile stop times to pattern stop changes

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java
Fixes #121.
Note: this updates patterns in the editor that have at least one referencing frequency trip to be "frequency-based."  What should be done if there are both frequency- and timetable-based trips referencing a single pattern?
=> Update use_frequency field for patterns on editor snapshot

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/JDBCFetcher.java, src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java, src/test/resources/graphql/feedRoutesAndTripsByTime.txt, src/test/resources/graphql/feedStopsStopTimeLimit.txt, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchNestedEntityWithLimit.json, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchRoutesAndFilterTripsByDateAndTime.json
- Allow filtering by date and time on the trips of a route in graphql.
- Fix a bug where the limit argument was not being properly applied in fetchers with autolimit set to false
Built off of the branch of PR #126
=> Graphql improvements

.travis.yml
This PR adds https://github.com/conveyal/maven-semantic-release to the travis build.
=> Semantic release

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
The `route_sort_order` field was added to the routes table as a part of PR #99, but the field wasn't added to the GraphQL schema.  This PR fixes that.
=> Add route_sort_order to graphql route_type fields

src/main/java/com/conveyal/gtfs/GTFS.java, src/main/java/com/conveyal/gtfs/loader/Table.java
This removes indexing for a couple of small tables, namely `agency` and `feed_info`.
Fixes #132.
=> Remove small table indexing

.travis.yml
maven-semantic-release v4.1.x+ now includes a verify-conditions step that checks if the maven project seems to be setup to be able to release to maven central.
=> Update to version 4.1.x of maven-semantic-release

pom.xml, src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/graphql/GraphQLUtil.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/FeedFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/JDBCFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/RowCountFetcher.java, src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java, src/test/resources/graphql/superNested.txt, src/test/resources/graphql/superNestedNoLimits.txt, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchMultiNestedEntities.json, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchMultiNestedEntitiesWithoutLimits.json
Take some very minor and reasonable changes that were included in #144 and call it good with updating graphQL a bit.
* Update GraphQL library from v4.2 to v11.0
* Add limit argument to routes nestedJdbcFetcher of stops
* Rename a few variables in JdbcFetcher so the query building makes more sense
* Add tests for highly nested GraphQL queries
=> Update GraphQL a little bit

src/main/java/com/conveyal/gtfs/validator/ServiceValidator.java, src/main/java/com/conveyal/gtfs/validator/ValidationResult.java
At first, I thought the variables `firstCalendarDate` and `lastCalendarDate` in the `ValidationResult` class were the first calendar date from the calendar_dates.txt file, but then I realized it was actually a result of calculating actual service of various days.  Renaming this variable should reflect this distinction and avoid future confusion.
=> Rename variable to avoid confusion

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/test/java/com/conveyal/gtfs/GTFSFeedTest.java, src/test/java/com/conveyal/gtfs/GTFSMainTest.java, src/test/java/com/conveyal/gtfs/GTFSTest.java, src/test/java/com/conveyal/gtfs/TestUtils.java, src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java
`registerFeed` calls `getCsvReader` which may add entries in `errorStorage`.
The code before may manipulate `errorStorage` before it is initialized, causing an exception to happen
on the above circumstance.
=> Fix error when loading GTFS with a subdirectory

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java, src/test/java/com/conveyal/gtfs/util/CalendarDTO.java, src/test/java/com/conveyal/gtfs/util/FrequencyDTO.java, src/test/java/com/conveyal/gtfs/util/PatternDTO.java, src/test/java/com/conveyal/gtfs/util/PatternStopDTO.java, src/test/java/com/conveyal/gtfs/util/ShapePointDTO.java, src/test/java/com/conveyal/gtfs/util/StopDTO.java, src/test/java/com/conveyal/gtfs/util/StopTimeDTO.java, src/test/java/com/conveyal/gtfs/util/TripDTO.java, src/test/java/com/conveyal/gtfs/util/UtilTest.java
In addition to some formatting tweaks and added comments, this seeks to address the underlying cause for conveyal/datatools-ui#385. It is another example of updates for "exemplar" fields not making their way back to the referencing entities (#109).
It also fixes #165, where stop_time arrivals and departures were not kept in sync with updates to the underlying pattern travel times. This is only a concern with frequency-based patterns, but the same method could potentially be utilized for updating travel times in timetable-based trips if needed in the future.
Finally, it adds some tests to `JdbcTableWriter` for creating frequency trips and fixes #173, which was discovered in the process of writing these tests.
=> Update trip#shape_id and frequency stop_times on pattern updates

src/main/java/com/conveyal/gtfs/model/StopTime.java, src/main/java/com/conveyal/gtfs/validator/SpeedTripValidator.java
We were missing a check for this field. It's relatively easy to check and I think it makes some sense to place this in the `SpeedTripValidator`. Fixes #163.
=> Validate stop_time#shape_dist_traveled

src/main/java/com/conveyal/gtfs/loader/Table.java
This closes #148 by increasing the max value and adding comments.
=> Increase headway seconds max to 6 hours

.travis.yml
This way it will upload a report for the code coverage after all the commits made with maven-semantic-release have completed.  Codecov looks at the most recent commit to master to compare the next report to, so this is needed for code coverage comparisons on PRs to master.
=> Run codecov after semantic-release

src/main/java/com/conveyal/gtfs/loader/EntityPopulator.java
This PR fixes #180. In the EntityPopulator, which grabs data from the RDBMS and populates the GTFS entity Java objects, missing values for fields of the double type where populating as `0.0` rather than `Entity.DOUBLE_MISSING`. This was causing our validation check for increasing stop_time#shape_dist_traveled values to cause issues where these values were entirely missing from a GTFS feed.
=> Fix missing double in EntityPopulator

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java
With this change, `JdbcGtfsExporter.cleanUpZipFile()` generates its file URI in a way that is portable across systems and avoids an `IllegalArgumentException` being thrown on Windows.
Fixes #170.
=> JdbcGtfsExporter: Fix exception in cleanUpZipFile() on Windows

.travis.yml, src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/FeedFetcher.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/JDBCFetcher.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java, src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/main/java/com/conveyal/gtfs/model/Pattern.java, src/main/java/com/conveyal/gtfs/validator/PatternFinderValidator.java, src/test/java/com/conveyal/gtfs/dto/CalendarDTO.java, src/test/java/com/conveyal/gtfs/dto/FareDTO.java, src/test/java/com/conveyal/gtfs/dto/FareRuleDTO.java, src/test/java/com/conveyal/gtfs/dto/FeedInfoDTO.java, src/test/java/com/conveyal/gtfs/dto/FrequencyDTO.java, src/test/java/com/conveyal/gtfs/dto/PatternDTO.java, src/test/java/com/conveyal/gtfs/dto/PatternStopDTO.java, src/test/java/com/conveyal/gtfs/dto/RouteDTO.java, src/test/java/com/conveyal/gtfs/dto/ShapePointDTO.java, src/test/java/com/conveyal/gtfs/dto/StopDTO.java, src/test/java/com/conveyal/gtfs/dto/StopTimeDTO.java, src/test/java/com/conveyal/gtfs/dto/TripDTO.java, src/test/java/com/conveyal/gtfs/dto/package-info.java, src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java, src/test/java/com/conveyal/gtfs/util/ShapePointDTO.java, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchPatterns.json, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchRoutes.json, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canSanitizeSQLInjectionSentAsKeyValue.json
~Once #190 is merged~ (it is merged!), I would like to create a new bug fix release.
#192 
#189
#170
#186
#187
=> Bug Fix Release

.travis.yml
In the latest merge to master, maven-semantic-release [failed during the Travis CI build](https://search.maven.org/solrsearch/select?q=com.conveyal.gtfs-lib&rows=20&wt=json). It looks like there was a poor internet connection. The build could probably just be reran and the internet will work again. However, there was an additional problem in that codecov reports were still uploaded for previous commits that were actually intended to be for commits from maven-semantic-release. This PR intends to run these extra codecov commands in the same script block so they won't be ran if maven-semantic-release fails.
=> After success refactor

src/main/java/com/conveyal/gtfs/loader/Field.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java, src/main/java/com/conveyal/gtfs/loader/Table.java
This PR modifies and makes static/public a few internal methods for `Table` and `JdbcTableLoader` that are used in https://github.com/conveyal/datatools-server/pull/186.
=> Tweaks for MTC enhancements

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/JDBCFetcher.java, src/test/java/com/conveyal/gtfs/GTFSFeedTest.java, src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java, src/test/resources/fake-agency/stops.txt, src/test/resources/graphql/feedStopWithChildren.txt, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchErrors.json, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchFeedRowCounts.json, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchNestedEntityWithLimit.json, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchStopWithChildren.json, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchStops.json
The GraphQL nested queries up until this change relied on parent tables with foreign refs sharing
the same field name as the primary key on the child table. For example, trips could be joined to a
route on the shared field route_id. This change permits nesting children stops under a parent stop
using stops#parent_station, which will be joined on the parent join value found in stops#stop_id.
refs conveyal/datatools-ui#428
=> Allow nested queries where field names don't  match

src/main/java/com/conveyal/gtfs/error/NewGTFSError.java, src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java, src/main/java/com/conveyal/gtfs/loader/BooleanField.java, src/main/java/com/conveyal/gtfs/loader/ColorField.java, src/main/java/com/conveyal/gtfs/loader/CurrencyField.java, src/main/java/com/conveyal/gtfs/loader/DateField.java, src/main/java/com/conveyal/gtfs/loader/DateListField.java, src/main/java/com/conveyal/gtfs/loader/DoubleField.java, src/main/java/com/conveyal/gtfs/loader/Field.java, src/main/java/com/conveyal/gtfs/loader/IllegalCharacter.java, src/main/java/com/conveyal/gtfs/loader/IntegerField.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/main/java/com/conveyal/gtfs/loader/LanguageField.java, src/main/java/com/conveyal/gtfs/loader/ShortField.java, src/main/java/com/conveyal/gtfs/loader/StringField.java, src/main/java/com/conveyal/gtfs/loader/StringListField.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/main/java/com/conveyal/gtfs/loader/TimeField.java, src/main/java/com/conveyal/gtfs/loader/URLField.java, src/main/java/com/conveyal/gtfs/loader/ValidateFieldResult.java, src/test/java/com/conveyal/gtfs/GTFSTest.java, src/test/java/com/conveyal/gtfs/loader/FieldTests.java, src/test/resources/fake-agency-bad-calendar-date/calendar_dates.txt
This PR fixes #191 by modifying how values encountered during GTFS loads are validated and cleaned. It uses a helper return class `ValidateFieldResult` to store both the cleaned value and any errors found during validation, which then are bubbled up and handled in `JdbcGtfsLoader`.
It also adds a new error type `ILLEGAL_FIELD_VALUE` to resolve the primary issue of not tracking instances where bad character sequences where found in a GTFS feed.
This also fixes #202.
=> Refactor field validation in order to store/validate bad values properly

src/main/java/com/conveyal/gtfs/loader/DateListField.java, src/test/java/com/conveyal/gtfs/dto/ScheduleExceptionDTO.java, src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java
fixes #214
A change to the return value for `Field#validate` (from String to ValidateFieldResult) caused an issue for creating/updating schedule exceptions with values for the `dates` field. This fixes the validate function and adds a CRUD test for schedule exceptions.
=> Fix schedule exceptions bug in DateListField

src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/graphql/fetchers/JDBCFetcher.java, src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java, src/test/resources/fake-agency-bad-calendar-date/stops.txt, src/test/resources/snapshots/com/conveyal/gtfs/graphql/GTFSGraphQLTest/canFetchStopsWithoutParentStationColumn.json
This fixes #217 by adapting a pre-existing method to check for the existence of columns in a table before adding a where clause that contains a missing column.
=> Omit where clauses containing columns missing from table

.travis.yml
Semantic-release v16 is going to have a breaking change that will make maven-semantic-release not work properly (see https://github.com/conveyal/maven-semantic-release/issues/10). Therefore this change preemptively fixes semantic-release to v15.x.x to prevent future breakage until maven-semantic-release can be updated to support semantic-release v16.
=> ci(semantic-release): pin semantic-release to v15

src/main/java/com/conveyal/gtfs/loader/Field.java
This PR fixes #228. If the illegal sequence encountered if an unescaped backslash, it will not record an ILLEGAL_FIELD_VALUE error, but otherwise behave the same (return a cleaned string for storage in the db).
=> Do not log error for unescaped backslashes

src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java
Some proprietary tables in the GTFS+ spec do not conform to the general principle in GTFS where a key field (e.g., stop_id) only acts as the primary key field in the entity's table. For example,
stop_id acts as a primary key on stop_attributes.txt, so we prepend the table name to the unique ID
for these tables when checking for duplicate entries.
=> Properly track primary keys in proprietary files

src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java
This PR contains a fixes #251 by qualifying the previously defined unique ID with the table name, rather than just containing the ordinal value.
=> fix(ReferenceTracker): add table name to full id

src/main/java/com/conveyal/gtfs/validator/SpeedTripValidator.java
Do not check for missing shape_dist_traveled value on the first stop time record in a sequence.
Many feeds omit this value instead of writing 0.0, which causes excessive noise in validation
results.
=> Fix false pos. missing stop_time#shape_dist_traveled

pom.xml
This package updates all plugins to their latest version and increases the timeout for deploying to nexus staging from 5 to 30 minutes. This will hopefully result in improved releases to OSSRH to make #254 go away.
=> Plugin update

pom.xml, src/main/java/com/conveyal/gtfs/GTFSMain.java, src/main/java/com/conveyal/gtfs/util/json/JsonManager.java
The Conveyal maven repo appears to no longer exist, so the GeoJSON Jackson module is no longer
available.
=> Remove Conveyal geojson module to fix Travis build/dep issue

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/test/java/com/conveyal/gtfs/GTFSTest.java
Fix #280 by setting skip empty records on the csv reader to false.
=> Do not skip empty lines in csv reader

src/main/java/com/conveyal/gtfs/GTFS.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/test/java/com/conveyal/gtfs/GTFSTest.java, src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java, src/test/java/com/conveyal/gtfs/storage/RecordExpectation.java
=> Add normalizeStopTimes flag to RDBMS snapshots preserve stop_sequence vals

src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java, src/test/java/com/conveyal/gtfs/GTFSTest.java
=> Mixed calendar definition fix ltr

src/main/java/com/conveyal/gtfs/error/NewGTFSError.java
There are a large number of useless exceptions being output to the log when adding NewGtfsError entries that do not have sequence values. This attempts to silence most of those. re ibi-group/datatools-server#342
=> Silence number excessive parse exceptions logs

src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/test/java/com/conveyal/gtfs/dto/RouteDTO.java, src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java
This PR addresses ibi-group/datatools-ui#619 and ibi-group/datatools-ui#616 by better handling empty string values passed to JdbcTableWriter for updates to GTFS entities. It also enhances tests to verify that `trip_id` is auto-generated for empty string literals.
=> Handle empty strings

.github/workflows/maven.yml
fix #306 by adding the `GH_TOKEN` env variable to the release step.
=> Add GH_TOKEN variable for semantic-release

src/main/java/com/conveyal/gtfs/error/NewGTFSError.java, src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java, src/main/java/com/conveyal/gtfs/loader/ConditionalCheckType.java, src/main/java/com/conveyal/gtfs/loader/ConditionalRequirement.java, src/main/java/com/conveyal/gtfs/loader/Field.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/main/java/com/conveyal/gtfs/loader/LineContext.java, src/main/java/com/conveyal/gtfs/loader/ReferenceTracker.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/test/java/com/conveyal/gtfs/loader/ConditionallyRequiredTest.java
Contains tweaks for #312. Namely:
- adds `LineContext` class to encapsulate some shared logic/clean things up
- renames some conditions/methods to be more concise/accurate (notably: conditionalField to dependentField)
- adds a new check method for `checkFieldEmpty`. I think the reference/dependent checks were mixed up, so as part of that I also reordered those (for routes#agency_id and fare_rules#agency_id)
- maybe a couple of other things... sorry if this went overboard!
FYI, some tests are broken. Happy to help resolve if help is needed!
=> Update conditional requirements checks

.github/workflows/maven.yml
Removes codecov reporting as we don't really use it anymore.
=> Remove codecov reporting

src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterTest.java
- [na] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
In this PR, `continuous_pickup` and `continuous_drop_off` linked fields in the `STOP_TIMES` table are set to be updated when a `PatternStop` entry is changed. This allows values in these fields to be exported to GTFS 2.0 archives in the Datatools GTFS editor.
=> Add stop_times linked fields continuous_pickup, continuous_drop_off.

src/main/java/com/conveyal/gtfs/GTFSFeed.java, src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, src/main/java/com/conveyal/gtfs/loader/EntityPopulator.java, src/main/java/com/conveyal/gtfs/loader/Feed.java, src/main/java/com/conveyal/gtfs/loader/FeedLoadResult.java, src/main/java/com/conveyal/gtfs/loader/JdbcGTFSFeedConverter.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsExporter.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java, src/main/java/com/conveyal/gtfs/loader/JdbcGtfsSnapshotter.java, src/main/java/com/conveyal/gtfs/loader/JdbcTableWriter.java, src/main/java/com/conveyal/gtfs/loader/Table.java, src/main/java/com/conveyal/gtfs/model/Entity.java, src/main/java/com/conveyal/gtfs/model/Location.java, src/main/java/com/conveyal/gtfs/model/LocationShape.java, src/main/java/com/conveyal/gtfs/util/GeoJsonUtil.java
This is a (very) rough PR which outlines a working prototype that allows saving of flex location shapes through parent 'locations' table. It builds on #335 and refactors mainly the Location, LocationShape, and (especially) the JdbcTableWriter classes.
=> Refactor location shapes to be saved with parent table Locations

src/main/java/com/conveyal/gtfs/loader/Table.java, src/test/java/com/conveyal/gtfs/GTFSTest.java
Fixes #339 
This PR removes the rounding to two decimal places which causes issue #339 and subsequent validation issues.
=> Remove rounding to 2 decimals in stop_times.shape_dist_traveled

src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java, src/main/java/com/conveyal/gtfs/validator/RouteTypeValidator.java, src/test/java/com/conveyal/gtfs/validator/RouteTypeValidatorTest.java
- [na] The description lists all applicable issues this PR seeks to resolve
- [na] The description lists any configuration setting(s) that differ from the default settings
This PR adds a validator for the `route_type` field in the `routes` table based on preconfigured values.
Constraints: Implementers must explicitly construct a `RouteTypeValidator` by providing the configured route types that they want to support, and they must explicitly invoke the validator's `validate` method to perform route type validation (let me know if that is too constraining). Invalid route types result in medium-severity errors.
=> feat(RouteTypeValidator): Add route type validation.
